#!/usr/bin/env bash
# configures an Ubuntu machine with nginx for two or more servers to respond with headers
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"

sudo REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
sudo ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "$STRING" > /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $REDIRECT" "$FILE"

sudo echo "$FOUR" > "$ERRORFILE"
sudo sed -i "37i\ $ERRORREDIRECT" "$FILE"

sudo sed -i "37i\ $CUSTOMHEADER" "$FILE"
sudo service nginx restart
