#!/usr/bin/env bash
# configures an Ubuntu machine with nginx for two or more servers to respond with headers
#FILE="/etc/nginx/sites-available/default"
#ERRORFILE="/usr/share/nginx/html/404error.html"

#REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
#ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
#CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

#STRING="Hello World!"
#FOUR="Ceci n'est pas une page"

#sudo apt-get -y update
#sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
#sudo echo "$STRING" > /var/www/html/index.nginx-debian.html
#sudo sed -i "37i\ $REDIRECT" "$FILE"

#sudo echo "$FOUR" > "$ERRORFILE"
#sudo sed -i "37i\ $ERRORREDIRECT" "$FILE"

#sudo sed -i "37i\ $CUSTOMHEADER" "$FILE"
#sudo service nginx restart

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "School" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://google.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
