#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
#sudo apt-get install -y software-properties-common
#sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
#sudo apt-get update
#sudo apt-get install -y haproxy=1.8.\*
#sudo echo "ENABLED=1" >> /etc/default/haproxy
#sudo mv /etc/haproxy/haproxy.cfg{,.original}
#sudo touch /etc/haproxy/haproxy.cfg
#printf %s "global
#    log 127.0.0.1 local0 notice
#    maxconn 2000
#    user haproxy
#    group haproxy

#defaults
#    log     global
#    mode    http
#    option  httplog
#    option  dontlognull
#    retries 3
#    option redispatch
#    timeout connect  5000
#    timeout client  10000
#    timeout server  10000
#
#listen hbnb
#    bind 0.0.0.0:80
#    mode http
#    stats enable
#    stats uri /haproxy?stats
#    balance roundrobin
#    option httpclose
#    option forwardfor
#    server 161176-web-01 54.242.163.85 check
#    server 161176-web-02 100.25.135.57 check
#" >> /etc/haproxy/haproxy.cfg
#sudo service haproxy start
sudo apt-get update
#installing HAPROXY
sudo apt-get -y install haproxy

# editing config file
sudo vi /etc/haproxy/haproxy.cfg

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 161176-web-01 54.242.163.85:80 check\n\tserver 161176-web-02 100.25.135.57:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
