#!/usr/bin/env bash
# Change ownership of necessary files and directories to nginx user
sudo chown -R nginx:nginx /var/www/html
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /var/log/nginx

# Modify the Nginx configuration file
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80/listen 8080/' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
